quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
    path('scraper/', include('scraperapp.urls'))
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

quoteapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    birth_date = models.DateField()
    birth_place = models.CharField(max_length=25)
    description = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Quote(models.Model):
    quote_text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

templates/quotes/add_quote.html
{% extends "includes/header.html" %}

{% block content %}
    
<div class="container mt-4">
    <h2>Add a New Quote</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_quote_text">Quote Text</label>
            <textarea class="form-control" id="id_quote_text" name="quote_text" placeholder="Enter quote text">{{ form.quote_text.value|default_if_none:'' }}</textarea>
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            <select class="form-control" id="id_author" name="author">
                {% for author in form.author.field.queryset %}
                <option value="{{ author.pk }}" {% if form.author.value == author.pk %} selected {% endif %}>{{ author.first_name }} {{ author.last_name }}</option>
                {% endfor %}
            </select>
        </div>
    
        <button type="submit" class="btn btn-primary mt-3">Submit</button>
    </form>
</div>
    
{% endblock %}