quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/<int:author_id>', views.detail_author, name='detail_author'),

]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
    path('scraper/', include('scraperapp.urls'))
]

scraperapp/urls.py
from django.urls import path
from . import views

app_name = 'scraperapp'

urlpatterns = [
    path('', views.scraper, name='scraper'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/includes/header.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes to Scrape App</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>
    <main class="container">
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'quoteapp:main' %}">Quotes to Scrape</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mynavbar">
                    <ul class="navbar-nav me-auto">
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quoteapp:add_author' %}">Add Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quoteapp:add_quote' %}">Add Quote</a>
                        </li>
                        
                    </ul>
                
                    <a href="{% url 'scraperapp:scraper' %}" class="btn btn-warning" style="margin-right: 10px"role="button">Scrap</a>
                
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}" class="btn btn-danger" style="margin-right: 10px"role="button">Logout</a>
                    {% else %}
                        <a href=" {% url 'users:login' %}" class="btn btn-success" style="margin-right: 10px" role="button">Login</a>
                    {% endif %}
                
                </div>
            </div>
        </nav>
    {% block content %} {% endblock %}
    </main>
</body>
</html>