quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/<int:author_id>', views.detail_author, name='detail_author'),

]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
    path('scraper/', include('scraperapp.urls'))
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/base.html
{% extends "includes/header.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Quotes</h2>
    {% for quote in quotes %}
        <div class="card mb-3">
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ quote.quote_text }}</p>
                    
                    <footer class="blockquote-footer">
                        <a href="{% url 'quoteapp:detail_author' quote.author.id %}">
                            {{ quote.author.first_name }} {{ quote.author.last_name }}
                        </a>
                    </footer>
                    
                </blockquote>
            </div>
            <div class="card-footer">
                {% for tag in quote.tags.all %}
                    <span class="badge bg-secondary">{{ tag.name }}</span>
                {% endfor %}
            </div>
        </div>
    {% empty %}
        <p class="text-center">No quotes available.</p>
    {% endfor %}

    <!-- Begin on Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if quotes.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">First</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotes.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">Previous</span>
                    </a>
                </li>
            {% endif %}

            {% for num in quotes.paginator.page_range %}
                {% if quotes.number == num %}
                    <li class="page-item active" aria-current="page"><span class="page-link">{{ num }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if quotes.has_next %}
                <li class="page-item">
                    <a class="page-link next" href="?page={{ quotes.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">Next</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotes.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">Last</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <!--End of Pagination -->
</div>
    
    
{% endblock %}